name: Update sfdx-project.json

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number for the package (e.g., 1.1.0.1)'
        required: true
        default: '20.25.35'
      packageVersionId:
        description: 'Subscriber Package Version ID'
        required: true
        default: '04tOs000000GYP7IAO'

jobs:
  update-sfdx-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get install jq
          
      # Set Git user identity based on the current user
      - name: Set Git user identity
        if: success()
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Extract Last Version Number
        if: success()
        id: extract-version
        run: |
          # Extract the last version number from sfdx-project.json
          LAST_VERSION=$(jq -r 'keys[] | select(startswith("code@"))' sfdx-project.json | sort | tail -n1 | sed 's/code@//')
          echo "Last version: $LAST_VERSION"

          # Increment the last version number (increase the build number)
          IFS='.' read -ra VERSION_PARTS <<< "$LAST_VERSION"
          VERSION_PARTS[3]=$((VERSION_PARTS[3] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}.${VERSION_PARTS[3]}"
          echo "New version: $NEW_VERSION"
          
          # Export the new version number for use in later steps
          echo "VERSION_NUMBER=$NEW_VERSION" >> $GITHUB_ENV
