name: Create Package

on:
  workflow_dispatch:
    inputs:
      packagename:
        required: true

jobs:
  Promote-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        id: step1

      - name: Install Salesforce CLI
        if: steps.step1.outcome == 'success'
        id: step2
        run: |
          sudo npm install -g @salesforce/cli

      # Step to authenticate with Salesforce Dev Hub
      - name: Authenticate with Dev Hub
        if: steps.step2.outcome == 'success'
        id: step3
        env:
          # SFDX_AUTH_URL is a secret stored in GitHub Secrets
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "Authenticating with Dev Hub updated"
          # Write the authentication URL to a file
          # Use the Salesforce CLI to authenticate with the org
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url --set-default --sfdx-url-stdin
