name: Salesforce CI/CD

on:
  workflow_dispatch:

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        id: step1

      - name: Install jq
        run: |
          sudo apt-get install jq

      - name: Install Salesforce CLI
        if: steps.step1.outcome == 'success'
        id: step2
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
          

      - name: Authenticate with Salesforce
        if: steps.step2.outcome == 'success'
        id: step3
        env:
          SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}
          SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
        run: |
          echo "$SF_PRIVATE_KEY" > server.key
          sfdx auth:jwt:grant --client-id $SF_CONSUMER_KEY --jwt-key-file server.key --username $SF_USERNAME --instance-url $SF_LOGIN_URL --alias my-hub-org

      - name: Create Package Version
        if: steps.step3.outcome == 'success'
        id: step4
        run: |
          echo "Creating package version for package: ${{ secrets.PACKAGE_NAME }} with version: ${{ github.sha }}"
          CREATE_OUTPUT=$(sfdx force:package:version:create --package ${{ secrets.PACKAGE_NAME }} --installation-key Sscdre1p --wait 10 -n ${{ github.sha }} --target-dev-hub shahidnewdev@clear.com --json)|| {
            echo "Failed to create package version"
            echo "Create Output: $CREATE_OUTPUT"
            exit 1
          }
          echo "Create Output: $CREATE_OUTPUT"
          PACKAGE_VERSION_ID=$(echo $CREATE_OUTPUT | jq -r '.result.SubscriberPackageVersionId')
          echo "PACKAGE_VERSION_ID=$PACKAGE_VERSION_ID" >> $GITHUB_ENV
