name: Show Me the S3cr3tz
on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Name of the package'
        required: false
        default: 'newPackageTest'
      versionNumber:
        description: 'Version number for the package (e.g., 1.1.0.1)'
        required: false
        default: '1.1.0.1'

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
        SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}
        SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
      run: |
        echo $PACKAGE_NAME >> secrets.txt
        echo $SFDX_AUTH_URL >> secrets.txt
        echo $SF_CONSUMER_KEY >> secrets.txt
        echo $SF_LOGIN_URL >> secrets.txt
        echo $SF_PRIVATE_KEY >> secrets.txt
        echo $SF_USERNAME >> secrets.txt
        
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
